name: Build and Test HLiNaCRbCsFr

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW64
      run: |
        choco install mingw -y
        $env:Path += ";C:\tools\mingw64\bin"

    - name: Build project with gcc
      run: |
        gcc -o HLiNaKRbCsFr.exe main.c banner.c help_functions.c  HLiNaKRbCsFr.h

  
